CREATE OR REPLACE PROCEDURE `rax-abo-72-dev`.sales.udsp_load_cloud_uk_contact_info()
begin


create or replace table `rax-abo-72-dev`.sales.cloud_uk_account_contact_info_current as
SELECT DISTINCT
    Cloud_Account_Key as Account_Key,
    Account_ID,
    SF_Account_ID,
    QA_Account_ID,
    Keizan_Core_Account,
    Keizan_Match_Date,
    Account_Number,
    SliceHost_CustomerID,
    AccountName,
    Account_Tenure,	
    Account_Status,
    Account_Status_ID,
    Account_Status_Online,
    Account_Status_Online_ID,
    Account_Type,
    Account_Type_ID,
    Account_SLAType,
    Account_SLATypeID,
    Account_Service_Level,
    Account_Service_Level_ID,
    Is_Managed_Flag,
    Account_SLA_Type_BRM_Desc,	    
    Account_SLA_Name_BRM,
    Account_SLA_Type_BRM,     
    Account_SLA_Type_BRM_Effective_Date,	
    Account_Created_Date,
    DesiredBillingDate AS Account_Desired_Billed_Date,
    Account_First_Billed_Date,
    Account_Last_Billed_Date,
    Account_End_Date,
    Keizan_Region,
    Keizan_Sub_Region,		
    Keizan_Business_Unit,
    Keizan_Segment,
    Keizan_Reporting_Segment,
    Keizan_Sub_Segment,
    Keizan_Cloud_Team,
    Keizan_Sub_Team,		
	Keizan_Cloud_AM,
    Keizan_Cloud_Onboarding_Specialist,
    Keizan_Cloud_Advisor,
    Keizan_Cloud_BDC,
    Keizan_Cloud_Tech_Lead,
	Keizan_Cloud_Sales_Associate,
    Keizan_Cloud_Launch_Manager,
    Keizan_Cloud_TAM,
    SF_Business_Unit,
    SF_GM,
    SF_VP,
    SF_Director,
    SF_Manager,
    SF_Segment,
    SF_Sub_Segment,
    SF_Team,
    SF_Account_Owner,
    SF_Account_Owner_EmployeeNumber,
    SF_Account_Source,
	ON_Net_Revenue_Plan,
    DesiredBillingDate,
    Consolidated_Billing										AS Consolidated_Billing,
    Consolidated_Create_Date,
    Keizan_Linked_Account,	
    Is_RackConnect_Linked,		
    FirstName,
    LastName,
    UserName,
    Email,
    Domain,
	Internal_Flag,
    Domain_Internal_Flag,
    
    Phone,
    Street,
    City,
    State,
    PostalCode,
    Country,
    CountryCode,	
    current_date()													As Load_Date	
FROM 
	`rax-abo-72-dev`.cloud_uk.cloud_account_contact_info_current A;

End;